package io.bootique.tools.release.model.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.exp.Property;

import io.bootique.tools.release.model.persistent.ClosedIssue;
import io.bootique.tools.release.model.persistent.GitHubEntity;
import io.bootique.tools.release.model.persistent.Milestone;
import io.bootique.tools.release.model.persistent.OpenIssue;
import io.bootique.tools.release.model.persistent.Organization;
import io.bootique.tools.release.model.persistent.ParentRepository;
import io.bootique.tools.release.model.persistent.PullRequest;

/**
 * Class _Repository was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Repository extends GitHubEntity {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> L_STATUS = Property.create("lStatus", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<LocalDateTime> PUSHED_AT = Property.create("pushedAt", LocalDateTime.class);
    public static final Property<String> PUSHED_AT_STR = Property.create("pushedAtStr", String.class);
    public static final Property<String> SSH_URL = Property.create("sshUrl", String.class);
    public static final Property<LocalDateTime> UPDATED_AT = Property.create("updatedAt", LocalDateTime.class);
    public static final Property<List<OpenIssue>> ISSUES = Property.create("issues", List.class);
    public static final Property<List<ClosedIssue>> ISSUES_CLOSE = Property.create("issuesClose", List.class);
    public static final Property<List<Milestone>> MILESTONES = Property.create("milestones", List.class);
    public static final Property<Organization> ORGANIZATION = Property.create("organization", Organization.class);
    public static final Property<ParentRepository> PARENT = Property.create("parent", ParentRepository.class);
    public static final Property<List<PullRequest>> PULL_REQUESTS = Property.create("pullRequests", List.class);

    protected String description;
    protected String lStatus;
    protected String name;
    protected LocalDateTime pushedAt;
    protected String pushedAtStr;
    protected String sshUrl;
    protected LocalDateTime updatedAt;

    protected Object issues;
    protected Object issuesClose;
    protected Object milestones;
    protected Object organization;
    protected Object parent;
    protected Object pullRequests;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String getDescription() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setLStatus(String lStatus) {
        beforePropertyWrite("lStatus", this.lStatus, lStatus);
        this.lStatus = lStatus;
    }

    public String getLStatus() {
        beforePropertyRead("lStatus");
        return this.lStatus;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setPushedAt(LocalDateTime pushedAt) {
        beforePropertyWrite("pushedAt", this.pushedAt, pushedAt);
        this.pushedAt = pushedAt;
    }

    public LocalDateTime getPushedAt() {
        beforePropertyRead("pushedAt");
        return this.pushedAt;
    }

    public void setPushedAtStr(String pushedAtStr) {
        beforePropertyWrite("pushedAtStr", this.pushedAtStr, pushedAtStr);
        this.pushedAtStr = pushedAtStr;
    }

    public String getPushedAtStr() {
        beforePropertyRead("pushedAtStr");
        return this.pushedAtStr;
    }

    public void setSshUrl(String sshUrl) {
        beforePropertyWrite("sshUrl", this.sshUrl, sshUrl);
        this.sshUrl = sshUrl;
    }

    public String getSshUrl() {
        beforePropertyRead("sshUrl");
        return this.sshUrl;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        beforePropertyWrite("updatedAt", this.updatedAt, updatedAt);
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getUpdatedAt() {
        beforePropertyRead("updatedAt");
        return this.updatedAt;
    }

    public void addToIssues(OpenIssue obj) {
        addToManyTarget("issues", obj, true);
    }

    public void removeFromIssues(OpenIssue obj) {
        removeToManyTarget("issues", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<OpenIssue> getIssues() {
        return (List<OpenIssue>)readProperty("issues");
    }

    public void addToIssuesClose(ClosedIssue obj) {
        addToManyTarget("issuesClose", obj, true);
    }

    public void removeFromIssuesClose(ClosedIssue obj) {
        removeToManyTarget("issuesClose", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ClosedIssue> getIssuesClose() {
        return (List<ClosedIssue>)readProperty("issuesClose");
    }

    public void addToMilestones(Milestone obj) {
        addToManyTarget("milestones", obj, true);
    }

    public void removeFromMilestones(Milestone obj) {
        removeToManyTarget("milestones", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Milestone> getMilestones() {
        return (List<Milestone>)readProperty("milestones");
    }

    public void setOrganization(Organization organization) {
        setToOneTarget("organization", organization, true);
    }

    public Organization getOrganization() {
        return (Organization)readProperty("organization");
    }

    public void setParent(ParentRepository parent) {
        setToOneTarget("parent", parent, true);
    }

    public ParentRepository getParent() {
        return (ParentRepository)readProperty("parent");
    }

    public void addToPullRequests(PullRequest obj) {
        addToManyTarget("pullRequests", obj, true);
    }

    public void removeFromPullRequests(PullRequest obj) {
        removeToManyTarget("pullRequests", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PullRequest> getPullRequests() {
        return (List<PullRequest>)readProperty("pullRequests");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "lStatus":
                return this.lStatus;
            case "name":
                return this.name;
            case "pushedAt":
                return this.pushedAt;
            case "pushedAtStr":
                return this.pushedAtStr;
            case "sshUrl":
                return this.sshUrl;
            case "updatedAt":
                return this.updatedAt;
            case "issues":
                return this.issues;
            case "issuesClose":
                return this.issuesClose;
            case "milestones":
                return this.milestones;
            case "organization":
                return this.organization;
            case "parent":
                return this.parent;
            case "pullRequests":
                return this.pullRequests;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "lStatus":
                this.lStatus = (String)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "pushedAt":
                this.pushedAt = (LocalDateTime)val;
                break;
            case "pushedAtStr":
                this.pushedAtStr = (String)val;
                break;
            case "sshUrl":
                this.sshUrl = (String)val;
                break;
            case "updatedAt":
                this.updatedAt = (LocalDateTime)val;
                break;
            case "issues":
                this.issues = val;
                break;
            case "issuesClose":
                this.issuesClose = val;
                break;
            case "milestones":
                this.milestones = val;
                break;
            case "organization":
                this.organization = val;
                break;
            case "parent":
                this.parent = val;
                break;
            case "pullRequests":
                this.pullRequests = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.lStatus);
        out.writeObject(this.name);
        out.writeObject(this.pushedAt);
        out.writeObject(this.pushedAtStr);
        out.writeObject(this.sshUrl);
        out.writeObject(this.updatedAt);
        out.writeObject(this.issues);
        out.writeObject(this.issuesClose);
        out.writeObject(this.milestones);
        out.writeObject(this.organization);
        out.writeObject(this.parent);
        out.writeObject(this.pullRequests);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.lStatus = (String)in.readObject();
        this.name = (String)in.readObject();
        this.pushedAt = (LocalDateTime)in.readObject();
        this.pushedAtStr = (String)in.readObject();
        this.sshUrl = (String)in.readObject();
        this.updatedAt = (LocalDateTime)in.readObject();
        this.issues = in.readObject();
        this.issuesClose = in.readObject();
        this.milestones = in.readObject();
        this.organization = in.readObject();
        this.parent = in.readObject();
        this.pullRequests = in.readObject();
    }

}
