package io.bootique.tools.release.model.maven.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import io.bootique.tools.release.model.maven.persistent.Module;

/**
 * Class _Dependency was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ModuleDependency extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> TYPE = Property.create("type", String.class);
    public static final Property<Module> MODULE = Property.create("module", Module.class);
    public static final Property<Module> ROOT_MODULE = Property.create("rootModule", Module.class);

    protected String type;

    protected Object module;
    protected Object rootModule;

    public void setType(String type) {
        beforePropertyWrite("type", this.type, type);
        this.type = type;
    }

    public String getType() {
        beforePropertyRead("type");
        return this.type;
    }

    public void setModule(Module module) {
        setToOneTarget("module", module, true);
    }

    public Module getModule() {
        return (Module)readProperty("module");
    }

    public void setRootModule(Module rootModule) {
        setToOneTarget("rootModule", rootModule, true);
    }

    public Module getRootModule() {
        return (Module)readProperty("rootModule");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "type":
                return this.type;
            case "module":
                return this.module;
            case "rootModule":
                return this.rootModule;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "type":
                this.type = (String)val;
                break;
            case "module":
                this.module = val;
                break;
            case "rootModule":
                this.rootModule = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.type);
        out.writeObject(this.module);
        out.writeObject(this.rootModule);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.type = (String)in.readObject();
        this.module = in.readObject();
        this.rootModule = in.readObject();
    }

}
